# Log src/main/resources/log4j2.xml
logging.config:

# Spring settings
spring:
    profiles.active: product

# SAIC2017
saic2017:
    mongo:
        hosts:
            - 127.0.0.1:27017
        source: admin # the source where the user is defined
        user: # your-user-name
        pwd: # your-password