# Log src/main/resources/log4j2.xml
logging.config:

# Spring settings
spring:
    profiles.active: product

# SAIC2017
saic2017:
    # 开始日期 yyyy-MM-dd
    beginDate: 2017-01-01
    # 结束日期
    endDate: 2017-12-31
    # 输出文件夹
    out: ./out
    # 是否把每天的输出结果打包
    enableTar: true
    # mongodb
    mongo:
        hosts:
            - 127.0.0.1:27017
        source: admin # the source where the user is defined
        user: # your-user-name
        pwd: # your-password
        database: newrvm
        collection: newrvmSignalData{date:yyyyMMdd}
    # 最大并发数
    maxPower: 8
    # 车辆数据模式,处理列在此处的,或不写表示全部处理
    modes:
        - AS24
        - AS26
        - IP24
        - IP34
        - OLD-AS24
        - IP32P
        - OLD-IP24MCE
        - OLD-IP24
        - OLD-BP34
    # 可以在测试时只处理指定的数据,或不写表示全部处理
    GB32960:
        - x01Overview
        - x02Motor
        - x04Engine
        - x05Position
        - x06Peak
        - x07Alarm
    # vin匹配正则表达式,可以在测试只处理匹配上的车辆,不写表示匹配全部
    vinMatch: # LSJA24793HS[0-9]+